### ISSUE TITLE
not rorking with BetterFriendList plugin

### ISSUE THREAD

**Issue by 3boodyxz** [CorellanStoma/Friends-Grid#5]
i trayd with hem or without hem and i think he is the reason of this proplem please fix it, thank you....
![2021 09 20-05 26](https://user-images.githubusercontent.com/44352802/133952081-d9004320-220d-4f2a-aa15-b597dbb1256f.png)

**Comment by Willy-JL** [comment]
You can keep using BetterFriendList by disabling the option `Adds mutual Servers in Friend List`  until this is fixed!
![image](https://user-images.githubusercontent.com/49810075/134070151-929c28aa-7ed6-4b73-a48b-6d5488412e8b.png)

**Comment by CorellanStoma** [comment]
> i trayd with hem or without hem and i think he is the reason of this proplem please fix it, thank you....
> ![2021 09 20-05 26](https://user-images.githubusercontent.com/44352802/133952081-d9004320-220d-4f2a-aa15-b597dbb1256f.png)

Hi, I'm currently working on a fix, which will appear the days, then there should be no more problems.

**Comment by 3boodyxz** [comment]
thank you for fix the problem
